global using MediatR;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Restaurants.API.Middlewares;
global using Restaurants.Application.Dtos.Dishes;
global using Restaurants.Application.Dtos.Restaurants;
global using Restaurants.Domain.Constants;
global using Restaurants.Infrastructure.Auth.Policies;
global using Serilog;
